// <auto-generated />
using FiapCloudGames.Users.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloudGames.Users.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiapCloudGamesUsersDbContext))]
    partial class FiapCloudGamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte>("UserType")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "adm@gmail.com",
                            Name = "Usuário Administrador",
                            Password = "$2y$10$0nJ0qFKXIeecwowh7sg53./xAESh24u0mM.NdJTT1b/TJ3FnS7Pym",
                            UserType = (byte)1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "comum@gmail.com",
                            Name = "Usuário Comum",
                            Password = "$2y$10$K1UygvGpjh9Mfw1z3PZemOQ8ltbEiZ5lHh8ugC9PcOa5wSKtount.",
                            UserType = (byte)0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
