apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: marioguilhermedev/users-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
  - port: 80
    targetPort: 8080
