name: Continuous integration - Fase de compilação e testes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Executando o Job de Compilação
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem do código fonte
        uses: actions/checkout@v4

      - name: Download do SDK do .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.x

      - name: Baixar as dependências (dotnet restore)
        run: dotnet restore FiapCloudGames.Games.sln

      - name: Compilar a aplicação
        run: dotnet build FiapCloudGames.Games.sln

      - name: Execução dos testes unitários
        run: dotnet test FiapCloudGames.Games.sln